export default [
  "",
  "Adult Intensivist",
  "Allergy/ Immunology ",
  "Anesthesia",
  "Anesthesiology",
  "Bariatric Medicine/Surgery",
  "Burn/Trauma",
  "Cardiac Catheterization",
  "Cardiology",
  "Cardiovascular Surgery",
  "Colon and rectal Surgery",
  "Critical Care Medicine",
  "Community Health",
  "Dermatology",
  "Dispensing Optics",
  "Electrophysiology",
  "Emergency Medicine",
  "Endocrinology",
  "Family Practice",
  "Family Physician",
  "Geriatrics",
  "Gynecologic Oncology",
  "Hematology/Oncology",
  "Hepatobiliary",
  "Hospice and Palliative Care",
  "Hospitalist",
  "Infectious Disease",
  "Internal Medicine",
  "Interventional Radiology",
  "Medical Genetics",
  "Medical Toxicology",
  "Neonatology",
  "Nephrology",
  "Neuroradiology",
  "Neurology",
  "Neurosurgery",
  "Nuclear Medicine",
  "Occupational Medicine",
  "Osteopathic Medicine",
  "Ophthalmology",
  "Otolaryngology / Head & Neck Surgery",
  "Pain Management",
  "Palliative Care",
  "Pathology: Surgical & Anatomic",
  "Pediatric Intensivist",
  "Pediatrics",
  "Pediatric Surgery",
  "Physical Medicine",
  "Physiotherapy",
  "Plastic & Reconstructive Surgery",
  "Pulmonary Medicine",
  "Radiation Oncology",
  "Radiology",
  "Rheumatology",
  "Reproduction & Infertility",
  "Surgical Oncology",
  "Thoracic Surgery",
  "Transplant Surgery",
  "Urology",
  "Nursing Care",
  "Vascular Surgery",
  "Wound Care",
  "ENT",
  "General Surgery",
  "Gastroenterology",
  "Obstetrics & Gynecology",
  "Oral/Dental Surgery",
  "Orthopedic Surgery",
  "Plastic Surgery",
  "Podiatric Surgery",
  "Preventive Medicine",
  "Psychiatry",
  "Pulmonology",
  "Ambulatory Clinics",
  "Diagnostic Radiology",
  "Emergency Department",
  "GI Endoscopy Labs",
  "Inpatient Acute Care",
  "Interventional Cardiology",
  "Same Day Surgery",
  "Small Specialty Hospitals",
  "Sleep Medicine",
  "Surgical Pathology",
  "HCC Audits",
  "Ambulance Coding",
  "Others",
]
